Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "AKIAJFJTUEJRJVN)"
    aws.secret_access_key = "zPP2NPXlYySrpA6IWbojChhPfhPSn7wWecc7/Ke1"
    aws.keypair_name = "vagrant-keypair"
    aws.

    aws.ami = "ami-5344d263"
    aws.region = "us-west-2"
    aws.instance_type = "t1.micro"
    aws.tags = {"working"=>"yes"}

    aws.security_groups = [ 'quick-start-1' ]

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/home/vagrant/vagrant-keypair.pem"
  end
end]
